server:
  port: 8092

node:
  node-id: node3
  static-nodes: #node2,localhost:8091
  ensure-peer-limit: false
  node-hostname: localhost
  node-port: 8092

miner:
  enabled: false
  difficulty: 4
  address: "gJUDBsklBkNscKGt3/oIxa6m82U="
  public-key: ${MINER_PUBLIC_KEY:}
