server:
  port: 8090

node:
  node-id: node1
  static-nodes: node2,localhost:8091
  node-hostname: localhost
  node-port: 8090

miner:
  enabled: true
  difficulty: 5
  address: "pawRn2srgWWEguTbdpo59Cc0QLk="
  public-key: ${MINER_PUBLIC_KEY:}