spring:
  application:
    name: Node
  websocket:
    max-text-message-size: 10MB
    max-binary-message-size: 10MB


  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/


  jpa:
    hibernate:
      ddl-auto: update


node:
  static-nodes: ${STATIC_NODES}
  peer-limit: ${PEER_LIMIT:3}
  node-id: ${NODE_ID:nodeId}
  node-hostname: ${NODE_HOSTNAME:nodeId}
  node-port: ${NODE_PORT}
  ensure-peer-limit: true
  gossip-peers: false
  unordered-blocks: false

miner:
  enabled: ${MINER_ENABLED:false}
  difficulty: ${MINER_DIFFICULTY:4}
  reward: ${MINER_REWARD:3}
  address: ${MINER_ADDRESS:}
  public-key: ${MINER_PUBLIC_KEY:}