server:
  port: 8090

node:
  node-id: node1
  static-nodes: #node2,localhost:8091
  node-hostname: localhost
  node-port: 8090

miner:
  enabled: false
  difficulty: 5
  address: "gJUDBsklBkNscKGt3/oIxa6m82U="
  public-key: ${MINER_PUBLIC_KEY:}